### PR TITLE
Update the dynamic tls records path

### PR DESCRIPTION
**Pull request by nename0**
[nginx-modules/ngx_http_tls_dyn_size](https://github.com/nginx-modules/ngx_http_tls_dyn_size) has added a patch for 1.15.3+.
I think we should use it

### CODE REVIEW

**Comment by nename0** [comment]
Thanks

**Comment by denji** [comment]
It seems to 1.15.5 also need to do the patch, since the semantics of the structure has changed.

**Comment by nename0** [comment]
Yeah
`git apply` fails to [do it](https://travis-ci.org/nename0/rpi-docker-nginx-boringssl/builds/439286363#L599)
`patch` on travis fails to [do it](https://travis-ci.org/nename0/rpi-docker-nginx-boringssl/builds/439297528#L601)
only `patch` in my git-bash (windows) worked

**Comment by nename0** [comment]
I updated the patch [now it works](https://travis-ci.org/nename0/rpi-docker-nginx-boringssl/builds/439309386#L598)
Source: https://github.com/nename0/ngx_http_tls_dyn_size/blob/patch-1/nginx__dynamic_tls_records_1.15.3%2B.patch

PR on nginx-modules/ngx_http_tls_dyn_size:
nginx-modules/ngx_http_tls_dyn_size#2

**Comment by nename0** [comment]
With https://cdn.rawgit.com/nginx-modules/ngx_http_tls_dyn_size/master/nginx__dynamic_tls_records_1.15.5%2B.patch it works again.
Thanks for your quick response!

**Pull request merged**
